# permissions for end users to edit krossboards.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: krossboard-editor-role
rules:
- apiGroups:
  - krossboard.krossboard.app
  resources:
  - krossboards
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - krossboard.krossboard.app
  resources:
  - krossboards/status
  verbs:
  - get
