apiVersion: krossboard.krossboard.app/v1alpha1
kind: Krossboard
metadata:
  name: krossboard
spec:
  koaImage: rchakode/kube-opex-analytics:24.03.3
  krossboardDataProcessorImage: krossboard/krossboard-data-processor:1.3.0
  krossboardUIImage: krossboard/krossboard-ui:1.2.1
  krossboardPersistentVolumeClaim: krossboard-data-pvc
  krossboardSecretName: krossboard-secrets