name: Docker image
on:
  pull_request:
    branches: [main]

jobs:
  build-image:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.19.0'    
    - name: Build and push Docker image
      env:
        IMAGE_REGISTRY_PASSWORD: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
        IMAGE_REGISTRY_USERNAME: ${{ secrets.IMAGE_REGISTRY_USERNAME }}
      run: |
        # Install controller-gen
        CTL_TOOLS_VERS=0.10.0
        wget -O controller-tools-${CTL_TOOLS_VERS}.zip https://github.com/kubernetes-sigs/controller-tools/archive/refs/tags/v${CTL_TOOLS_VERS}.zip
        unzip controller-tools-${CTL_TOOLS_VERS}.zip
        cd controller-tools-${CTL_TOOLS_VERS}/cmd/controller-gen
        go build -o controller-gen main.go
        export PATH=$PWD:$PATH

        # Build image
        cd -
        export IMAGE_TAG="$(date +%F)-$(git rev-parse --short HEAD)"
        sed -i -r 's/(VERSION\s\?=\s)[0-9]+\.[0-9]+\.[0-9]+/\1'$IMAGE_TAG'/' Makefile

        echo "$IMAGE_REGISTRY_PASSWORD" | docker login -u $IMAGE_REGISTRY_USERNAME --password-stdin
        make build docker-build docker-push