name: Docker image
on:
  pull_request:
    branches: [main]

jobs:
  build-image:
    runs-on: ubuntu-20.04
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-go@v3
      with:
        go-version: '>=1.18.0'    
    - name: Build and push Docker image
      env:
        DOCKERHUB_PASSWORD: ${{ secrets.IMAGE_REGISTRY_PASSWORD }}
        DOCKERHUB_USERNAME: ${{ secrets.IMAGE_REGISTRY_USERNAME }}
      run: |
        export IMAGE_TAG="$(date +%F)-$(git rev-parse --short HEAD)"
        sed -i -r 's/(VERSION\s\?=\s)[0-9]+\.[0-9]+\.[0-9]+/\1'$IMAGE_TAG'/' Makefile
        make build docker-build docker-push